server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
    client:
      registrerWitheureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZonr: http://localhost:8070/eureka/